config:
    required: true

database:
    +:
        name: default
        package: src.Model
        namespace: App\Model
        defaultIdMethod: native
        identifierQuoting: true

    +vendor:
        type: mysql
        parameters:
            Engine: InnoDB
            Charset: utf8

    +behavior:
        - auto_add_pk

    content_block:
        data: longvarchar

    user:
        type: tinyint
        first_name: text
        last_name: text
        middle_name: text
        email: varchar(255)
        phone: varchar(255)
        password: varchar(255)
        salt: varchar(255)
        +behavior:
            - timestampable

    user_access_token:
        user_id: int > user.id
        token: varchar(64) key
        refresh_token: varchar(64) key
        expired_at: - datetime
        +behavior:
            - timestampable

    user_group:
        title: varchar(255)
        name: varchar(50) key(10)
        roles: array

    user_group_rel:
        user_id: int > user.id
        user_group_id: int > user_group.id
