version: '3.4'

services:
    db:
        image: mariadb:10
        command: mysqld --sql-mode='' --max-prepared-stmt-count=65528 --innodb-flush-log-at-trx-commit=2 --character-set-server=utf8 --collation-server=utf8_general_ci
        volumes:
            - db:/var/lib/mysql:cached
        ports:
            - 3306
        environment:
            MYSQL_USER: '${DATABASE_USER}'
            MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
            MYSQL_DATABASE: '${DATABASE_NAME}'

volumes:
    db:
